language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

addons:
  apt:
    packages:
      - graphviz

notifications:
  email: false
  irc:
    channels:
      - "irc.iiens.net#Clicky"
    on_success: change
    on_failure: always

before_script:
  - rm -rf vendor/
  - rm composer.lock
  - composer self-update -n
  - composer install -n

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/phpcs
